title = "Pouriya Jahanbakhsh"
baseURL = "http://localhost"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Pouriya Jim Jahanbakhsh"
  description = "All about Pouriya Jim Jahanbakhsh"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = "The source code is available on GitHub"
    url = "https://github.com/pouriya/pouriya.net"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-twitter"
    title = "Twitter"
    url = "https://twitter.com/mr_pouriya"

[permalinks]
  "/" = "/:filename"

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = 'pastie'
    tabWidth = 4
